### ISSUE TITLE
feathers-offline-realtime CDN ?

### ISSUE THREAD

**Issue by abalad** [feathersjs/feathers-offline-realtime#14]
Is there a cdn for this repository equal to the feathers.js Client?

**Comment by subodhpareek18** [comment]
Why don't you try https://unpkg.com, it kind of works with any npm module. 
for eg: https://unpkg.com/feathers-offline-realtime

**Comment by subodhpareek18** [comment]
Though on second thought, we need UMD build for unpkg to work. Which this repo might not have.

**Comment by subodhpareek18** [comment]
@eddyystop ?

**Comment by eddyystop** [comment]
Anyone want to submit a PR?
