### ISSUE TITLE
Question:  What are you using for the offline database?

### ISSUE THREAD

**Issue by delebash** [feathersjs/feathers-offline-realtime#15]
I don't see IndexDb being used in your code and was wondering how you store the offline data?

**Comment by eddyystop** [comment]
The repo is designed to use an injected client-side Feathers service. For
the moment however its using its own in-memory custom service.

First, I want to reduce the number of moving parts until we're sure the
repo is solid. Second, I've been waiting on a project that's building a JS
friendly indexed store to run on the server, browser, Android and iOS.
