### ISSUE TITLE
Migrate the guides and documentations to the latest version of docs.feathersjs.com

### ISSUE THREAD

**Issue by heypoom** [feathersjs/feathers-offline-realtime#20]
It seems like the guides and docs are currently in [Feathers Auk's documentation site](https://auk.docs.feathersjs.com/guides/offline-first/configure-snapshot.html), which is now outdated as it is superseded by [Feathers Buzzard](https://docs.feathersjs.com). Also, the GitHub pages for [feathers-plus/offline-realtime](https://feathers-plus.github.io/v1/offline-realtime) seems to be nonexistent.

As this package still works great, I suggest moving the guides and docs to the latest version of feathers' site, so that it will be easier for others to find.

P.S. I found a more [detailed version of the documentation](https://github.com/feathers-plus/feathers-offline-realtime/tree/v0.1.0) in the older v0.1.0 tag too.

**Comment by laurensiusadi** [comment]
I wonder if this repo is still usable
